<?php


namespace App\AdminModule\Presenters;


use Nette;
use App;


abstract class BasePresenter extends App\Presenters\BasePresenter
{

	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub

		if( ! $this->user->isLoggedIn() )
		{
			$this->flashMessage( 'Pred vstupom do administrácie sa musíte prihlásiť.', 'info' );
			$this->redirect( ':Front:Sign:in' );
		}
	}

}
