<?php

namespace App\AdminModule\Presenters;


use Kdyby\Doctrine\EntityManager;
use Kdyby\Doctrine\EntityRepository;
use Nette;
use App;
use Tracy\Debugger;


class GaleryPresenter extends App\AdminModule\Presenters\BasePresenter
{

	const ITEMS_PER_PAGE = 8;

	/** @var  EntityManager @inject */
	public $em;

	/** @var  EntityRepository */
	public $uploadArticleRepository;

	/** @var  App\AdminModule\Forms\ArticlesUploadFormFactory @inject */
	public $articleUploadFormFactory;

	/** @var  int */
	public $id = NULL;


	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub
		$this->uploadArticleRepository = $this->em->getRepository( App\Model\Entity\ArticleUpload::class );
	}


	public function renderArticle( $id )
	{
		$this->id = $id;
		$images = $this->uploadArticleRepository->findBy( ['articles_id' => $id], 'id ASC' );
		$this->template->images = $this->setPaginator( $images );
		$this->template->page = $this['vp']->getPaginator()->page;  // Because of tinymce needs to know page.

	}


	public function renderProduct( $id )
	{
		$this->id = $id;
		$images = $this->images->uploadProductsRepository->findBy( ['products_id' => $id], 'id ASC' );
		$this->template->images = $this->setPaginator( $images );
		$this->template->page = $this['vp']->getPaginator()->page;  // Because of tinymce needs to know page.

	}


///////Protected/////////////////////////////////////////////////////////////

	protected function setPaginator( $images )
	{
		$vp = $this['vp'];
		$paginator = $vp->getPaginator();
		$paginator->itemsPerPage = self::ITEMS_PER_PAGE;
		$paginator->itemCount = $images->count();

		return $images->limit( $paginator->itemsPerPage, $paginator->offset );

	}

////// Components ////////////////////////////////////////////////////////////

	public function createComponentArticleUploadForm()
	{
		return $this->articleUploadFormFactory->create( $this->id );
	}

}
